version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jovoco_postgres
    environment:
      POSTGRES_USER: jovoco_user
      POSTGRES_PASSWORD: jovoco_password
      POSTGRES_DB: jovoco_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jovoco_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
